apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
spec:
  template:
    metadata:
      name: didox-ecommerce
      labels:
        app: didox-ecommerce
    spec:
      containers:
        - name: container-didox-ecommerce
          image: didox/ecommerce-treinamento-ibm:v0.0.3
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi" # 512 MB
              cpu: "0.5" # 1 milicors VCPU # este recurso tira do meu cluster este recurso #https://www.datacenters.com/news/what-is-a-vcpu-and-how-do-you-calculate-vcpu-to-cpu https://www.hyve.com/what-is-a-vmware-vcpu/
            limits: # caso a aplicação precise de mais recurso, ele coloca este limite automático
              memory: "800Mi" # 800 MB
              cpu: "0.6"
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_HOST

            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DATABASE_ECOMERCE

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_USER

            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: db-mysql-secret
                  key: MYSQL_ROOT_PASSWORD

  replicas: 2
  selector:
    matchLabels:
      app: didox-ecommerce
