apiVersion: v1
kind: Pod
metadata:
  name: didox-nginx-volume
spec:
  containers:
    - name: nginx-volume
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
