apiVersion: v1
kind: Pod
metadata:
  name: didox-mysql
  labels:
    app: didox-mysql
spec:
  containers:
    - name: container-pod-mysql
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: aadfg3gm5ikn
        - name: MYSQL_DATABASE
          value: ecommerce